{
  "Settings": [
    {
      "Name": "OrchestratorSystemCredential",
      "Value": "COEA-1234_SAP_Credential",
      "Description": "Nome da Credencial utilizada no processo"
    },
    {
      "Name": "OrchestratorSystemCredentialFolder",
      "Value": "GrupoCCR/CSC/Tesouraria",
      "Description": "Pasta da credencial utilizada no processo"
    },
    {
      "Name": "logF_BusinessProcessName",
      "Value": "COEA-1234_Download de Comprovantes",
      "Description": "Logging field which allows grouping of log data of two or more subprocesses under the same business process name"
    },
    {
      "Name": "OrchestratorQueueName",
      "Value": "FILA_ATRPA-1234_Step2_SAP",
      "Description": "Nome da Fila no Orchestrator"
    },
    {
      "Name": "OrchestratorQueueFolder",
      "Value": "GrupocCCR/CSC/Tesouraria",
      "Description": "Nome da Pasta onde está localizada a Fila no Orchestrator"
    },
    {
      "Name": "OrchestratorNextQueueName",
      "Value": "FILA_ATRPA-1234_Step2_SAP",
      "Description": "Nome da próxima fila de step do Processo (Para onde irão os itens de sucesso para continuar o processo)"
    },
    {
      "Name": "OrchestratorNextQueueFolder",
      "Value": "GrupocCCR/CSC/Tesouraria",
      "Description": "Nome da Pasta onde está localizada a Fila no Orchestrator"
    },
    {
      "Name": "OrchestratorLastQueueName",
      "Value": "FILA_ATRPA-1234_Step2_SAP",
      "Description": "Nome da última fila do processo (Para onde deverão ser enviados os itens de exceção)"
    },
    {
      "Name": "OrchestratorLastQueueFolder",
      "Value": "GrupocCCR/CSC/Tesouraria",
      "Description": "Nome da Pasta onde está localizada a Fila no Orchestrator"
    }
  ],
  "Constants": [
    {
      "Name": "ExceptionMessage_ConsecutiveErrors",
      "Value": "O número máximo de Exceções de Sistema consecutivas foi atingido!",
      "Description": "Mensagem de erro caso o MaxConsecutiveSystemExceptions seja alcaçado"
    },
    {
      "Name": "ExScreenshotsFolderPath",
      "Value": "Print_Excecoes",
      "Description": "Local para salvar print de exceções - Pode ser um caminho completo ou relativo"
    },
    {
      "Name": "LogMessage_ApplicationException",
      "Value": "Exceção de Sistema",
      "Description": "Parte estática da mensagem de registro no LOG. Processed Transaction failed with application exception."
    },
    {
      "Name": "LogMessage_BusinessRuleException",
      "Value": "Exceção de Negócios",
      "Description": "Parte estática da mensagem de registro no LOG. Processed Transaction failed with business exception."
    },
    {
      "Name": "LogMessage_GetTransactionData",
      "Value": "Processando Transação Número: ",
      "Description": "Parte estática da mensagem de registro no LOG. Calling Get Transaction Data."
    },
    {
      "Name": "LogMessage_GetTransactionDataError",
      "Value": "Erro ao obter dados da Transação Número: ",
      "Description": "Parte estática da mensagem de registro no LOG. Error retrieving Transaction Data."
    },
    {
      "Name": "LogMessage_Success",
      "Value": "Transação Completa!",
      "Description": "Parte estática da mensagem de registro no LOG. Processed Transaction succesful."
    },
    {
      "Name": "MaxConsecutiveSystemExceptions",
      "Value": "0",
      "Description": "O número de exceções consecutivas do sistema permitidas. Se MaxConsecutiveSystemExceptions for atingido, o trabalho será interrompido. Para desabilitar esse recurso, defina o valor como 0."
    },
    {
      "Name": "MaxRetryNumber",
      "Value": "0",
      "Description": "Deve ser 0 se estiver trabalhando com filas do Orchestrator. Se > 0, o robô tentará novamente a mesma transação que falhou com uma exceção do sistema. Deve ser um valor inteiro."
    },
    {
      "Name": "RetryNumberGetTransactionItem",
      "Value": "1",
      "Description": "O número de vezes que a atividade Get Transaction Item é tentada novamente em caso de uma exceção. Deve ser um inteiro >= 1."
    },
    {
      "Name": "RetryNumberSetTransactionStatus",
      "Value": "1",
      "Description": "O número de vezes que a atividade Set transaction status é tentada novamente em caso de uma exceção. Deve ser um inteiro >= 1."
    },
    {
      "Name": "ShouldMarkJobAsFaulted",
      "Value": "TRUE",
      "Description": "Deve ser TRUE ou FALSE. Se o valor for TRUE e ocorrer um erro no estado Initialization ou MaxConsecutiveSystemExceptions for atingido, o trabalho será marcado como Faulted. NÃO ALTERAR"
    }
  ],
  "Assets": [
    {
      "Name": "Global_KillProcess",
      "Asset": "GLOBAL_KILLALLPROCESS",
      "OrchestratorAssetFolder": "GrupoCCR",
      "Description": "Asset padrão para a atividade de KillAllProcesses"
    }
  ]
}